language: python
services: docker

env:
  global:
    - ROLE_NAME: ansibullbot-instance
  matrix:
    # - MOLECULE_DISTRIBUTION: centos6
    - MOLECULE_DISTRIBUTION: centos7
    # - MOLECULE_DISTRIBUTION: ubuntu16
    # - MOLECULE_DISTRIBUTION: ubuntu18
    # - MOLECULE_DISTRIBUTION: debian8
    # - MOLECULE_DISTRIBUTION: debian9

install:
  - pip install molecule docker

before_script:
  # Remove "ansible-role-" prefix from role name
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  # Run tests
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
