- name: Find AMI
  ec2_ami_find:
    name: "CentOS Linux 7*"
    owner: 410186602215
    region: "{{ botinstance_region }}"
    sort: name
    sort_order: descending
    sort_end: 1
  register: _amifind
  tags:
    - botinstance
    - always

- include: "{{ botinstance_cloud }}/{{ botinstance_action }}.yml"
